name: First Workflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: windows-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!
      - name: Print Goodbye
        run: echo "Bye!"

      
